import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './contexts/**/*.{js,ts,jsx,tsx,mdx}',
    './hooks/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      xs:  '480px',
      sm:  '640px',
      md:  '768px',
      lg:  '1024px',
      xl:  '1280px',
      '2xl': '1536px',
    },
    extend: {
      // ── Color System ──────────────────────────────────────────────────────
      colors: {
        'tertiary-fixed': 'rgb(var(--tertiary-fixed) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container) / <alpha-value>)',
        'surface-tint': 'rgb(var(--surface-tint) / <alpha-value>)',
        'on-secondary': 'rgb(var(--on-secondary) / <alpha-value>)',
        'error': 'rgb(var(--error) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--inverse-primary) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--on-secondary-fixed) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--on-secondary-container) / <alpha-value>)',
        'surface-dim': 'rgb(var(--surface-dim) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest) / <alpha-value>)',
        'on-error-container': 'rgb(var(--on-error-container) / <alpha-value>)',
        'surface-variant': 'rgb(var(--surface-variant) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--on-tertiary-fixed) / <alpha-value>)',
        'secondary': 'rgb(var(--secondary) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--inverse-surface) / <alpha-value>)',
        'background': 'rgb(var(--background) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest) / <alpha-value>)',
        'on-error': 'rgb(var(--on-error) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--primary-fixed-dim) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--surface-container-high) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--on-tertiary-container) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--primary-fixed) / <alpha-value>)',
        'on-background': 'rgb(var(--on-background) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--on-tertiary) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant) / <alpha-value>)',
        'tertiary': 'rgb(var(--tertiary) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant) / <alpha-value>)',
        'primary': 'rgb(var(--primary) / <alpha-value>)',
        'surface-bright': 'rgb(var(--surface-bright) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--on-secondary-fixed-variant) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--tertiary-container) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--on-primary-fixed-variant) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--secondary-fixed-dim) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--on-tertiary-fixed-variant) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--on-primary-fixed) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--secondary-fixed) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--inverse-on-surface) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--tertiary-fixed-dim) / <alpha-value>)',
        'surface': 'rgb(var(--surface) / <alpha-value>)',
        'secondary-container': 'rgb(var(--secondary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container) / <alpha-value>)',
        'outline': 'rgb(var(--outline) / <alpha-value>)',
        // Keeping legacy vars just in case they're referenced somewhere not yet refactored
        void:          'rgb(var(--bg-void) / <alpha-value>)',
        elevated:      'rgb(var(--bg-elevated) / <alpha-value>)',
        subtle:        'rgb(var(--bg-subtle) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '1rem',
        'space-sm': '0.375rem',
        'space-lg': '0.875rem',
        gutter: '0.75rem',
        'space-xs': '0.25rem',
        'space-xl': '1.25rem',
        'space-md': '0.625rem',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'telemetry-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'telemetry-lg': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Inter', 'sans-serif'],
        'label-lg': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'telemetry-sm': ['0.8125rem', { lineHeight: '1rem', fontWeight: '500' }],
        'headline-lg': ['1.25rem', { lineHeight: '1.625rem', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-sm': ['0.75rem', { lineHeight: '1.05rem', fontWeight: '400' }],
        'label-caps': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.06em', fontWeight: '600' }],
        'telemetry-lg': ['1.875rem', { lineHeight: '2rem', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-md': ['1.05rem', { lineHeight: '1.375rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['1.5rem', { lineHeight: '1.875rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.04em', fontWeight: '500' }],
        'body-lg': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'label-sm': ['0.625rem', { lineHeight: '0.75rem', letterSpacing: '0.06em', fontWeight: '500' }],
        'headline-sm': ['0.9375rem', { lineHeight: '1.125rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['0.8125rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      // ── Keyframes ─────────────────────────────────────────────────────────
      keyframes: {
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(245, 166, 35, 0.28)' },
          '50%':       { boxShadow: '0 0 24px 8px rgba(245, 166, 35, 0.28)' },
        },
      },
      // ── Animations ────────────────────────────────────────────────────────
      animation: {
        'pulse-glow': 'pulseGlow 2.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
