services:
  db:
    image: postgres:16-alpine
    container_name: shooting-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shooting_platform
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - shooting_db_data:/var/lib/postgresql/data

volumes:
  shooting_db_data:
