services:
  - type: web
    name: marksman-api
    env: node
    buildCommand: npm install && npm run build:api
    startCommand: cd apps/api && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false

  - type: web
    name: marksman-web
    env: node
    buildCommand: npm install && npm run build:web
    startCommand: cd apps/web && npm run start
    envVars:
      - key: NODE_ENV
        value: production