"""
Mask R-CNN bullet-hole detector for pixel-precise centroid estimation.

Role in the pipeline
--------------------
Mask R-CNN provides TWO things CV and plain YOLO cannot:

1. Pixel-level segmentation mask — the exact outline of each bullet hole,
   not just a bounding box. The mask centroid is more accurate than the
   bounding-box centre, especially for irregular tear shapes.

2. Independent detection — can find holes that CV missed (low contrast
   in cream zone) or YOLO missed (novel lighting conditions).

Architecture
------------
Uses torchvision.models.detection.maskrcnn_resnet50_fpn (ResNet-50 + FPN
backbone + Mask head). Fine-tuned on synthetic bullet holes generated by
tests/generate_synthetic.py.

Inference strategy
------------------
To stay fast on CPU, the detector runs on a downsampled version of the
target (max 800 px on longest side) and maps coordinates back to the
working image resolution.

Graceful fallback
-----------------
If torch / torchvision is not installed the module sets _mask_available=False
and detect_holes_mask() returns [] — the pipeline continues CV+YOLO only.

Model path: models/maskrcnn_holes.pth
"""

import logging
import os
import math
from typing import List, Optional, Tuple

import cv2
import numpy as np

from .types import FusedHole, TargetCalibration

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Module-level state
# ---------------------------------------------------------------------------

_mask_model = None
_mask_available: bool = False
_mask_device = None
_INFER_MAX_DIM = 800    # resize to this before MaskRCNN inference (speed/accuracy trade-off)
_CONF_THRESHOLD = 0.50  # minimum mask score to retain


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def load_mask_model(
    model_path: str = "models/maskrcnn_holes.pth",
) -> bool:
    """
    Load the fine-tuned Mask R-CNN model.

    Returns True on success, False if torch / file unavailable.
    Safe to call multiple times.
    """
    global _mask_model, _mask_available, _mask_device

    if not os.path.exists(model_path):
        logger.info("Mask R-CNN model not found at %s", model_path)
        return False

    try:
        import torch
        import torchvision

        _mask_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Build same architecture used during training (1 class = bullet_hole)
        _mask_model = _build_maskrcnn(num_classes=2)  # 1 class + background
        state = torch.load(model_path, map_location=_mask_device)
        _mask_model.load_state_dict(state)
        _mask_model.to(_mask_device)
        _mask_model.eval()

        _mask_available = True
        logger.info("Mask R-CNN loaded from %s on %s", model_path, _mask_device)
        return True

    except ImportError:
        logger.info("torch/torchvision not installed — Mask R-CNN unavailable")
        return False
    except Exception as exc:
        logger.warning("Failed to load Mask R-CNN: %s", exc)
        return False


def detect_holes_mask(
    gray: np.ndarray,
    calibration: TargetCalibration,
    target_type: str,
    conf_threshold: float = _CONF_THRESHOLD,
) -> List[FusedHole]:
    """
    Run Mask R-CNN inference and return pixel-precise hole detections.

    Args:
        gray:           Grayscale working image.
        calibration:    Target calibration (used for ROI focus).
        target_type:    "air_rifle_10m" | "air_pistol_10m" | …
        conf_threshold: Minimum mask confidence to keep.

    Returns:
        List of FusedHole (method="mask").  Empty if model not loaded.
    """
    if not _mask_available or _mask_model is None:
        return []

    try:
        import torch
    except ImportError:
        return []

    h, w = gray.shape[:2]

    # Downscale for inference speed
    scale = min(1.0, _INFER_MAX_DIM / max(h, w))
    if scale < 1.0:
        work = cv2.resize(gray, None, fx=scale, fy=scale,
                          interpolation=cv2.INTER_AREA)
    else:
        work = gray.copy()
        scale = 1.0

    wh, ww = work.shape[:2]

    # Focus on target area (±10% beyond outer ring radius)
    cx, cy = calibration.center
    r_focus = calibration.major_radius * 1.10 * scale
    cx_s, cy_s = cx * scale, cy * scale
    x1 = max(0, int(cx_s - r_focus))
    y1 = max(0, int(cy_s - r_focus))
    x2 = min(ww, int(cx_s + r_focus))
    y2 = min(wh, int(cy_s + r_focus))
    roi = work[y1:y2, x1:x2]
    if roi.size == 0:
        return []

    # Prepare tensor: (1, 3, H, W) float32 in [0,1]
    rgb_roi = cv2.cvtColor(roi, cv2.COLOR_GRAY2RGB)
    tensor = (
        torch.from_numpy(rgb_roi.transpose(2, 0, 1))
        .float()
        .div(255.0)
        .unsqueeze(0)
        .to(_mask_device)
    )

    with torch.no_grad():
        outputs = _mask_model(tensor)

    result = outputs[0]
    boxes   = result["boxes"].cpu().numpy()     # (N, 4) xyxy in roi space
    scores  = result["scores"].cpu().numpy()    # (N,)
    masks   = result["masks"].cpu().numpy()     # (N, 1, H_roi, W_roi)

    holes: List[FusedHole] = []
    for i in range(len(scores)):
        if float(scores[i]) < conf_threshold:
            continue

        # Binary mask at 0.5 threshold
        mask_bin = masks[i, 0] > 0.5
        if not np.any(mask_bin):
            continue

        # Precise centroid from mask moments
        ys, xs = np.where(mask_bin)
        mask_cx_roi = float(xs.mean())
        mask_cy_roi = float(ys.mean())

        # Effective radius from mask area (circle-equivalent)
        area = float(np.sum(mask_bin))
        mask_r = math.sqrt(area / math.pi)

        # Map from ROI space → full working image space
        mask_cx = (mask_cx_roi + x1) / scale
        mask_cy = (mask_cy_roi + y1) / scale

        holes.append(FusedHole(
            x=mask_cx,
            y=mask_cy,
            radius=mask_r / scale,
            confidence=float(scores[i]),
            methods_agreed=1,
            method="mask",
        ))

    return holes


# ---------------------------------------------------------------------------
# Model architecture
# ---------------------------------------------------------------------------

def _build_maskrcnn(num_classes: int = 2):
    """
    Build a Mask R-CNN with ResNet-50 FPN backbone.

    num_classes includes background (class 0) + bullet_hole (class 1).
    """
    import torchvision
    from torchvision.models.detection import maskrcnn_resnet50_fpn, MaskRCNN_ResNet50_FPN_Weights
    from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
    from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor

    # Pre-trained COCO weights — we'll fine-tune the heads
    model = maskrcnn_resnet50_fpn(weights=MaskRCNN_ResNet50_FPN_Weights.DEFAULT)

    # Replace box predictor head
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

    # Replace mask predictor head
    in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    hidden_layer = 256
    model.roi_heads.mask_predictor = MaskRCNNPredictor(
        in_features_mask, hidden_layer, num_classes
    )

    return model
